/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChmiRadarConfigRouteImport } from './routes/api/chmi/radar-config'
import { Route as ApiChmiLayerRouteImport } from './routes/api/chmi/layer'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChmiRadarConfigRoute = ApiChmiRadarConfigRouteImport.update({
  id: '/api/chmi/radar-config',
  path: '/api/chmi/radar-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChmiLayerRoute = ApiChmiLayerRouteImport.update({
  id: '/api/chmi/layer',
  path: '/api/chmi/layer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/chmi/layer': typeof ApiChmiLayerRoute
  '/api/chmi/radar-config': typeof ApiChmiRadarConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/chmi/layer': typeof ApiChmiLayerRoute
  '/api/chmi/radar-config': typeof ApiChmiRadarConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/chmi/layer': typeof ApiChmiLayerRoute
  '/api/chmi/radar-config': typeof ApiChmiRadarConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/chmi/layer' | '/api/chmi/radar-config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/chmi/layer' | '/api/chmi/radar-config'
  id: '__root__' | '/' | '/admin' | '/api/chmi/layer' | '/api/chmi/radar-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiChmiLayerRoute: typeof ApiChmiLayerRoute
  ApiChmiRadarConfigRoute: typeof ApiChmiRadarConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chmi/radar-config': {
      id: '/api/chmi/radar-config'
      path: '/api/chmi/radar-config'
      fullPath: '/api/chmi/radar-config'
      preLoaderRoute: typeof ApiChmiRadarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chmi/layer': {
      id: '/api/chmi/layer'
      path: '/api/chmi/layer'
      fullPath: '/api/chmi/layer'
      preLoaderRoute: typeof ApiChmiLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiChmiLayerRoute: ApiChmiLayerRoute,
  ApiChmiRadarConfigRoute: ApiChmiRadarConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
